id: P005630
initial_creation_type: ocr
source_metadata:
  id: bdr:W21586
  title: གཟུགས་ཀྱི་ཉི་མའི་རྣམ་ཐར།
  author: ''
  volumes:
    5e2742f610184cb9801c5dab1862b639:
      image_group_id: I1KG21881
      title: ''
      volume_number: 1
      total_pages: 114
