id: P005630
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 12:08:18.329876
source_metadata:
  id: bdr:W21586
  title: གཟུགས་ཀྱི་ཉི་མའི་རྣམ་ཐར།
  author: ''
  volumes:
    5e2742f610184cb9801c5dab1862b639:
      image_group_id: I1KG21881
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
