id: I945E491B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T01:08:01+00:00'
last_modified: '2022-06-08T05:25:19.154757+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21586
  title: གཟུགས་ཀྱི་ཉི་མའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    84CC:
      image_group_id: I1KG21881
      title: ''
      total_pages: 114
      order: 1
      base_file: 84CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
